name: Monitorar Site

on:
  schedule:
    - cron: "*/2 * * * *"  # a cada 10 minutos
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt
      - name: Executar monitor
        run: python monitor.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  
      - name: Salvar hash como artefato
        uses: actions/upload-artifact@v4
        with:
          name: hash-site
          path: hash.txt

